from typing import Protocol
from uuid import UUID

from app.domain.corpus_read import CorpusCatalogue, CorpusSlice, EntityView, EpisodeView, SourceView, ThreadView, TopicDetail, TopicNode


class CorpusReadPort(Protocol):
    """Stable F0.4 read contract for F0.6 and future export adapters."""

    def list_topics(self, run_id: UUID) -> list[TopicNode]: ...

    def get_topic(self, run_id: UUID, topic_id: UUID) -> TopicDetail | None: ...

    def get_topic_children(self, run_id: UUID, topic_id: UUID) -> list[TopicNode]: ...

    def get_topic_ancestors(self, run_id: UUID, topic_id: UUID) -> list[TopicNode]: ...

    def get_topic_episodes(self, run_id: UUID, topic_id: UUID) -> list[EpisodeView]: ...

    def get_episode(self, run_id: UUID, episode_id: UUID) -> EpisodeView | None: ...

    def get_source(self, run_id: UUID, source_id: UUID) -> SourceView | None: ...

    def get_thread(self, run_id: UUID, thread_id: UUID) -> ThreadView | None: ...

    def get_entity(self, run_id: UUID, entity_id: UUID) -> EntityView | None: ...

    def get_corpus_slice(self, run_id: UUID, topic_id: UUID, include_descendants: bool = True) -> CorpusSlice: ...

    def get_catalogue(self, run_id: UUID) -> CorpusCatalogue: ...
