from collections.abc import Sequence
from datetime import datetime
from typing import Protocol, runtime_checkable
from uuid import UUID

from app.domain.semantic import (
    Entity,
    Episode,
    EpisodeEntity,
    EpisodeRelation,
    EpisodeTopic,
    OrganizerRun,
    Thread,
    ThreadEpisode,
    Topic,
    TopicRelation,
)


@runtime_checkable
class SemanticWritePort(Protocol):
    """Storage-independent write contract for derived organizer data."""

    def create_run(self, run: OrganizerRun) -> None: ...

    def write_episodes(self, episodes: Sequence[Episode]) -> None: ...

    def write_entities(self, entities: Sequence[Entity]) -> None: ...

    def write_topics(self, topics: Sequence[Topic]) -> None: ...

    def write_episode_relations(self, relations: Sequence[EpisodeRelation]) -> None: ...

    def write_threads(self, threads: Sequence[Thread]) -> None: ...

    def write_episode_entities(self, links: Sequence[EpisodeEntity]) -> None: ...

    def write_episode_topics(self, links: Sequence[EpisodeTopic]) -> None: ...

    def write_topic_relations(self, relations: Sequence[TopicRelation]) -> None: ...

    def write_thread_episodes(self, links: Sequence[ThreadEpisode]) -> None: ...

    def complete_run(self, run_id: UUID, finished_at: datetime) -> None: ...

    def fail_run(self, run_id: UUID, finished_at: datetime, error: str) -> None: ...


@runtime_checkable
class SemanticReadPort(Protocol):
    """Storage-independent read contract for derived organizer data."""

    def get_run(self, run_id: UUID) -> OrganizerRun | None: ...

    def get_episodes(self, run_id: UUID) -> list[Episode]: ...

    def get_entities(self, run_id: UUID) -> list[Entity]: ...

    def get_topics(self, run_id: UUID) -> list[Topic]: ...

    def get_episode_relations(self, run_id: UUID) -> list[EpisodeRelation]: ...

    def get_threads(self, run_id: UUID) -> list[Thread]: ...

    def get_episode_entities(self, run_id: UUID) -> list[EpisodeEntity]: ...

    def get_episode_topics(self, run_id: UUID) -> list[EpisodeTopic]: ...

    def get_topic_relations(self, run_id: UUID) -> list[TopicRelation]: ...

    def get_thread_episodes(self, run_id: UUID) -> list[ThreadEpisode]: ...
